name: trigger action
on:
  push:
     branches:    
      - main
     tags:
     - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node and run node application
        uses: actions/setup-node@v3
      
      - name: to run read.js
        run: node read.js
        
      - name: to fetch tags
        run: git fetch --tags
        
      
