name: trigger action
on:
  push:
     branches:    
      - main
     tags:
     - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
    
      - name: to run read.js
        working-directory: 01_SourceCode
        run: node read.js ${{ github.ref }}

      - run: |
              echo "${{ github.action }}"
              echo "${{ github.event }}"
              echo "${{ github.event_name }}"
              echo "${{ github.ref }}"
        
      - name: to fetch tags
        run: git fetch --tags
        
      - name: to list docker images
        run: docker images
        
      
